export const industries = {
  electronics: {
    label: "Electronics",
    categories: [
      "Phones & Tablets", "Laptops & Computers", "Audio & Headphones",
      "Cameras & Photography", "Gaming", "TV & Home Theatre", "Accessories",
    ],
    heroTagline: "Latest Tech. Best Prices.",
    heroSubtitle: "Genuine products, fast delivery across Nigeria.",
    trustBadges: [
      { icon: "shield-check", text: "1-Year Warranty" },
      { icon: "package-check", text: "Genuine Products" },
      { icon: "truck", text: "Fast Delivery" },
      { icon: "rotate-ccw", text: "Easy Returns" },
    ],
    colors: { primary: "#1D4ED8", secondary: "#3B82F6" },
    brands: ["Apple", "Samsung", "Sony", "LG", "Huawei", "Xiaomi", "Dell", "HP", "Tecno", "Infinix"],
    productColors: ["#000000", "#FFFFFF", "#C0C0C0", "#1D4ED8", "#DC2626", "#16A34A"],
    sizes: ["64GB", "128GB", "256GB", "512GB", '32"', '43"', '55"', '65"'],
    styles: ["Wireless", "Wired", "Portable", "Desktop", "Gaming"],
    patterns: ["Matte", "Glossy", "Metallic"],
  },

  fashion: {
    label: "Fashion & Apparel",
    categories: ["Women", "Men", "Kids & Baby", "Shoes", "Bags & Luggage", "Watches", "Accessories"],
    heroTagline: "Style That Moves You.",
    heroSubtitle: "Trending fashion, delivered to your door.",
    trustBadges: [
      { icon: "rotate-ccw", text: "Free Returns" },
      { icon: "badge-check", text: "Authentic Brands" },
      { icon: "zap", text: "Same-Day Delivery" },
      { icon: "lock", text: "Secure Payment" },
    ],
    colors: { primary: "#BE185D", secondary: "#EC4899" },
    brands: ["Nike", "Adidas", "Zara", "H&M", "Puma", "Gucci", "Levi's", "Primark"],
    productColors: ["#000000", "#FFFFFF", "#DC2626", "#1D4ED8", "#16A34A", "#F59E0B", "#EC4899", "#8B4513"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL", "3XL", "36", "38", "40", "42", "44"],
    styles: ["Casual", "Formal", "Sportswear", "Party", "Office", "Evening"],
    patterns: ["Solid", "Striped", "Printed", "Floral", "Checked", "Plain"],
  },

  grocery: {
    label: "Grocery & Food",
    categories: [
      "Fruits & Vegetables", "Meat & Fish", "Dairy & Eggs",
      "Beverages", "Snacks & Confectionery", "Grains & Staples", "Household",
    ],
    heroTagline: "Fresh. Fast. Delivered.",
    heroSubtitle: "Farm-fresh groceries at your doorstep.",
    trustBadges: [
      { icon: "zap", text: "Same-Day Delivery" },
      { icon: "leaf", text: "Farm Fresh" },
      { icon: "thermometer", text: "Cold Chain Guaranteed" },
      { icon: "shield-check", text: "Quality Assured" },
    ],
    colors: { primary: "#15803D", secondary: "#22C55E" },
    brands: ["Nestlé", "Unilever", "Dangote", "Chi", "Indomie", "Dano", "Peak", "Milo"],
    productColors: ["#16A34A", "#F59E0B", "#DC2626", "#FFFFFF"],
    sizes: ["250g", "500g", "1kg", "2kg", "5kg", "10L", "20L"],
    styles: ["Organic", "Frozen", "Fresh", "Packaged", "Bulk"],
    patterns: ["Single", "Pack of 6", "Pack of 12", "Carton"],
  },

  beauty: {
    label: "Beauty & Personal Care",
    categories: ["Skincare", "Makeup", "Hair Care", "Fragrances", "Nail Care", "Men's Grooming", "Wellness"],
    heroTagline: "Beauty Made for You.",
    heroSubtitle: "100% authentic beauty products for every skin tone.",
    trustBadges: [
      { icon: "badge-check", text: "100% Authentic" },
      { icon: "heart", text: "Dermatologist Tested" },
      { icon: "gift", text: "Free Samples" },
      { icon: "rotate-ccw", text: "Easy Returns" },
    ],
    colors: { primary: "#9333EA", secondary: "#A855F7" },
    brands: ["Nivea", "L'Oréal", "Maybelline", "MAC", "Dove", "Neutrogena", "OAN", "Vaseline"],
    productColors: ["#FFC0CB", "#FFFFFF", "#F5F5DC", "#8B4513", "#FF69B4", "#FF0000"],
    sizes: ["30ml", "50ml", "100ml", "150ml", "200ml", "250ml", "500ml"],
    styles: ["Moisturizing", "Anti-aging", "Brightening", "Matte", "Shimmer", "Natural"],
    patterns: ["Light", "Medium", "Full Coverage", "SPF 15", "SPF 30", "SPF 50"],
  },

  furniture: {
    label: "Furniture & Home",
    categories: ["Living Room", "Bedroom", "Kitchen & Dining", "Office", "Outdoor", "Lighting", "Decor"],
    heroTagline: "Furnish Your Story.",
    heroSubtitle: "Quality furniture built for Nigerian homes.",
    trustBadges: [
      { icon: "wrench", text: "Free Assembly" },
      { icon: "shield-check", text: "Quality Guaranteed" },
      { icon: "rotate-ccw", text: "Easy Returns" },
      { icon: "truck", text: "Nationwide Delivery" },
    ],
    colors: { primary: "#92400E", secondary: "#D97706" },
    brands: ["Ashley", "IKEA", "Homepro", "WoodHub", "Decozone", "Artcraft"],
    productColors: ["#8B4513", "#D2B48C", "#808080", "#000000", "#FFFFFF", "#1D4ED8"],
    sizes: ["Small", "Medium", "Large", "King", "Queen", "Single", "Double"],
    styles: ["Modern", "Classic", "Scandinavian", "Industrial", "Rustic", "Minimalist"],
    patterns: ["Plain", "Tufted", "Woven", "Carved", "Upholstered"],
  },

  general: {
    label: "General Marketplace",
    categories: ["Electronics", "Fashion", "Home & Garden", "Sports & Fitness", "Books & Education", "Toys & Games"],
    heroTagline: "Everything You Need.",
    heroSubtitle: "Shop thousands of products. Fast delivery everywhere.",
    trustBadges: [
      { icon: "truck", text: "Free Delivery" },
      { icon: "rotate-ccw", text: "Easy Returns" },
      { icon: "headphones", text: "24/7 Support" },
      { icon: "lock", text: "Secure Payment" },
    ],
    colors: { primary: "#000040", secondary: "#22C55E" },
    brands: ["Sony", "Samsung", "LG", "Apple", "Xiaomi", "Electrolux", "Daikin", "Hitachi"],
    productColors: ["#000000", "#FFFFFF", "#808080", "#DC2626", "#1D4ED8", "#16A34A", "#F59E0B", "#FF69B4"],
    sizes: ["XS", "S", "M", "L", "XL", "One Size"],
    styles: ["Classic", "Modern", "Casual", "Premium"],
    patterns: ["Plain", "Printed", "Patterned"],
  },
}
